version: "3.2"

services:
  backend:
    container_name: grpc-backend
    image: node:10
    ports:
      - "3000:3000"
    volumes:
      - .:/server
    command: sh -c 'cd /server && yarn && yarn dev'
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://mongo:27017/assignment1
    depends_on:
      - mongo

  mongo:
    container_name: grpc-mongo
    image: mongo:4
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongodb:/data/db
      - ./volumes/mongodb_config:/data/configdb